apiVersion: apps/v1
kind: Deployment
metadata:
 name: todo-webapp
spec:
 replicas: 1
 selector:
   matchLabels:
     app: todo-webapp
 template:
   metadata:
     labels:
       app: todo-webapp
   spec:
     containers:
     - name: todo-container
       image: ghcr.io/larsappel/todoapp:01b8388a83c1b91b501f1b367ba1dd7be7842d87
       ports:
       - containerPort: 80
       envFrom: 
       - configMapRef:
           name: app-config